spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: 'jdbc:h2:./todo-db'
